[build]
  command = "pnpm build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_PUBLIC_SUPABASE_URL = "https://aqirdonqsbmcwcqeyrop.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxaXJkb25xc2JtY3djcWV5cm9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxNDU0MjQsImV4cCI6MjA3MTcyMTQyNH0.uOAZz0jGjbMuLrkpj9HoeEWe5QsSHpaXIaE2TfTWQpU"
  
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"