-- Insert sample leather products with proper category references
INSERT INTO public.products (
  name, slug, description, short_description, price, compare_at_price, 
  category_id, image_url, stock_quantity, sku, material, color, 
  is_featured, is_active
) VALUES 
-- Luxury Products
(
  'Premium Italian Leather Handbag',
  'premium-italian-leather-handbag',
  'Exquisite handcrafted Italian leather handbag made from the finest full-grain leather. Features elegant gold hardware and silk lining.',
  'Handcrafted Italian leather handbag with gold hardware',
  299.99,
  399.99,
  (SELECT id FROM public.categories WHERE slug = 'designer-handbags'),
  '/placeholder.svg?height=400&width=400',
  15,
  'LUX-HB-001',
  'Full-grain Italian leather',
  'Cognac Brown',
  true,
  true
),
(
  'Executive Leather Wallet',
  'executive-leather-wallet',
  'Premium executive wallet crafted from top-grain leather with RFID blocking technology. Multiple card slots and bill compartments.',
  'Premium leather wallet with RFID protection',
  89.99,
  119.99,
  (SELECT id FROM public.categories WHERE slug = 'luxury-wallets'),
  '/placeholder.svg?height=400&width=400',
  25,
  'LUX-WL-001',
  'Top-grain leather',
  'Black',
  true,
  true
),
(
  'Designer Leather Belt',
  'designer-leather-belt',
  'Sophisticated leather belt with brushed metal buckle. Perfect for business and formal occasions.',
  'Designer leather belt with metal buckle',
  149.99,
  199.99,
  (SELECT id FROM public.categories WHERE slug = 'premium-belts'),
  '/placeholder.svg?height=400&width=400',
  20,
  'LUX-BT-001',
  'Full-grain leather',
  'Dark Brown',
  true,
  true
),
-- Everyday Products
(
  'Classic Leather Wallet',
  'classic-leather-wallet',
  'Durable everyday leather wallet with multiple card slots and cash compartment. Perfect for daily use.',
  'Classic leather wallet for everyday use',
  39.99,
  49.99,
  (SELECT id FROM public.categories WHERE slug = 'standard-wallets'),
  '/placeholder.svg?height=400&width=400',
  50,
  'STD-WL-001',
  'Genuine leather',
  'Brown',
  false,
  true
),
(
  'Work Leather Gloves',
  'work-leather-gloves',
  'Heavy-duty leather work gloves designed for durability and protection. Reinforced palms and fingers.',
  'Durable leather work gloves',
  24.99,
  29.99,
  (SELECT id FROM public.categories WHERE slug = 'work-gloves'),
  '/placeholder.svg?height=400&width=400',
  100,
  'STD-GL-001',
  'Split leather',
  'Natural',
  false,
  true
),
(
  'Casual Leather Backpack',
  'casual-leather-backpack',
  'Stylish leather backpack perfect for daily commute or casual outings. Multiple compartments and laptop sleeve.',
  'Casual leather backpack with laptop compartment',
  79.99,
  99.99,
  (SELECT id FROM public.categories WHERE slug = 'casual-bags'),
  '/placeholder.svg?height=400&width=400',
  30,
  'STD-BP-001',
  'Genuine leather',
  'Black',
  false,
  true
);
